import { Metadata } from 'next';
import Link from 'next/link';
import { buildMetadata } from '../../../../lib/seo/metadata';

export const metadata: Metadata = buildMetadata({ path: '/docs/implementation', title: 'Implementation Guide | Oxiom Invoice Processing', description: 'Implementation guide for deploying Oxiom Invoice Processing. Phases, timeline, data migration, training, go-live checklist.' });

const phases = [
  ['Phase 1: Planning (2 weeks)', 'Confirm requirements, document current-state AP workflows, identify stakeholders, and define invoice data mapping requirements.'],
  ['Phase 2: Configuration (2 weeks)', 'Set up the environment, establish user roles, configure approval workflows, and align validation rules with policy expectations.'],
  ['Phase 3: Data Migration (1 week)', 'Load historical invoice records and vendor master data needed for continuity, searchability, and validation accuracy.'],
  ['Phase 4: Testing (1 week)', 'Run user acceptance testing, integration testing, exception-path validation, and workflow sign-off with AP, accounting, and IT stakeholders.'],
  ['Phase 5: Training (1 week)', 'Deliver end-user training, administrator training, approver enablement, and support-readiness sessions before cutover.'],
  ['Phase 6: Go-Live', 'Execute production cutover, monitor the hypercare period, track open issues daily, and confirm stable invoice processing before closing the implementation project.'],
];

const metrics = ['Invoice processing cycle time', 'Touchless or low-touch processing rate', 'Exception volume and resolution time', 'Approver turnaround time', 'Backlog aging and payment-ready throughput'];

export default function ImplementationGuidePage() {
  return <div className="min-h-screen bg-white"><div className="border-b border-slate-100 bg-slate-50 py-12 sm:py-16"><div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10"><h1 className="mb-4 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">Implementation Guide</h1><p className="max-w-3xl text-lg text-slate-600">A phased deployment guide for finance, AP, and IT teams introducing Oxiom Invoice Processing into production operations.</p></div></div><div className="mx-auto max-w-7xl px-6 py-16 sm:px-8 sm:py-20 lg:px-10"><section className="mb-16 space-y-6">{phases.map(([title, body]) => (<div key={title} className="rounded-lg border border-slate-200 bg-white p-6"><h2 className="mb-3 text-2xl font-semibold text-slate-950">{title}</h2><p className="text-base leading-7 text-slate-600">{body}</p></div>))}</section><section className="mb-16 grid gap-10 lg:grid-cols-2"><div><h2 className="mb-4 text-3xl font-semibold text-slate-950">Post-launch optimization</h2><p className="text-base leading-7 text-slate-600">After go-live, review throughput, exception patterns, and approval delays weekly. Use hypercare findings to refine validation rules, saved worklists, training, and escalation thresholds over the first 30 to 90 days.</p></div><div><h2 className="mb-4 text-3xl font-semibold text-slate-950">Success metrics</h2><div className="rounded-lg border border-slate-200 bg-slate-50 p-6"><ul className="space-y-3 text-sm leading-6 text-slate-600">{metrics.map((metric) => (<li key={metric} className="flex gap-3"><span className="mt-1 text-blue-700">•</span><span>{metric}</span></li>))}</ul></div></div></section></div><div className="border-t border-slate-100 bg-slate-50 py-16 sm:py-20"><div className="mx-auto max-w-5xl px-6 sm:px-8 lg:px-10"><div className="grid gap-6 md:grid-cols-3"><Link href="/docs/admin" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Administrator guide</h3></Link><Link href="/docs/api" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">API documentation</h3></Link><Link href="/support" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Support hub</h3></Link></div></div></div></div>;
}
