import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Getting Started with Oxiom | Invoice Processing Setup Guide', description: 'Quick start guide for Oxiom Invoice Processing. Set up your account, upload your first invoice, and learn the workflow in under 30 minutes.' };

const steps = [
  ['Step 1: Access your workspace', 'Sign in through your organization-specific Oxiom login URL, confirm your role-based access, and use the dashboard overview to review pending invoices, queue volumes, and recent activity.'],
  ['Step 2: Upload your first invoice', 'Open Upload from the navigation, drag in a PDF, JPEG, PNG, or TIFF invoice, and confirm the file enters the intake queue with source and receipt details attached.'],
  ['Step 3: Track invoice through workflow', 'Monitor the invoice as it moves through Received → Processing → Verified → Approved → Payment-Ready → Paid so you can see exactly where work is happening and where follow-up is needed.'],
  ['Step 4: Use search to find invoices', 'Use global search and filters to find invoices by supplier, amount, status, location, approver, or invoice number without manually scanning worklists.'],
  ['Step 5: Review exceptions and resolve issues', 'Open exception queues to resolve duplicates, missing fields, validation mismatches, or approval blockers before they affect processing deadlines.'],
];

const checklist = ['Confirm your login URL, MFA status, and user role.', 'Review dashboard KPI cards.', 'Upload a sample invoice.', 'Verify the invoice appears in the queue.', 'Open the invoice detail view.', 'Practice filtering by status and supplier.', 'Save a recurring search.', 'Review exception handling steps.', 'Identify your approver path.', 'Bookmark the support hub.'];

export default function GettingStartedPage() {
  return <div className="min-h-screen bg-white"><div className="border-b border-slate-100 bg-slate-50 py-12 sm:py-16"><div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10"><h1 className="mb-4 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">Getting started with Oxiom Invoice Processing</h1><p className="max-w-3xl text-lg text-slate-600">Launch your first invoice workflow quickly with a practical onboarding path for AP analysts, approvers, and finance operations teams.</p></div></div><div className="mx-auto max-w-7xl px-6 py-16 sm:px-8 sm:py-20 lg:px-10"><section className="mb-16 grid gap-6 md:grid-cols-2 xl:grid-cols-5">{steps.map(([title, description]) => (<div key={title} className="rounded-lg border border-slate-200 bg-white p-6"><h2 className="mb-3 text-xl font-semibold text-slate-950">{title}</h2><p className="text-sm leading-6 text-slate-600">{description}</p></div>))}</section><section className="mb-16 grid gap-10 lg:grid-cols-2"><div><h2 className="mb-6 text-3xl font-semibold text-slate-950">Onboarding checklist</h2><div className="rounded-lg border border-slate-200 bg-slate-50 p-6"><ul className="space-y-3 text-sm leading-6 text-slate-600">{checklist.map((item) => (<li key={item} className="flex gap-3"><span className="mt-1 text-blue-700">✓</span><span>{item}</span></li>))}</ul></div></div><div><h2 className="mb-6 text-3xl font-semibold text-slate-950">Next steps</h2><div className="grid gap-6"><Link href="/docs/user-guide" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-xl font-semibold text-slate-950">User Guide</h3></Link><Link href="/docs/admin" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-xl font-semibold text-slate-950">Administrator Guide</h3></Link><Link href="/faq" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-xl font-semibold text-slate-950">FAQ</h3></Link><Link href="/support" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-xl font-semibold text-slate-950">Getting help</h3><p className="text-sm text-slate-600">Visit the support hub for contact options, SLA details, and troubleshooting resources.</p></Link></div></div></section></div></div>;
}
