/**
 * Growth Intelligence Platform -- shared contract types.
 *
 * A social-listening and engagement-workflow tool for Oxiom's own
 * marketing team: discover public discussions, draft a starting-point
 * reply for a human to review and personalize, and track what happens
 * after a human actually posts it themselves. See lib/growth/README.md
 * for the full model and the hard guarantee that nothing in this module
 * ever posts to an external platform.
 */

export type OpportunityId = string;
export type DraftReplyId = string;
export type PublishedEngagementId = string;

/** Free-form, not a closed union -- same reasoning as EngineCapability in
 * the Engine Framework: the platform must not hardcode which sources
 * exist. 'manual' is the only platform this milestone actually
 * implements a source for. */
export type Platform = string;

export type OpportunityCategory =
  | 'question'
  | 'recommendation-request'
  | 'complaint'
  | 'competitor-comparison'
  | 'feature-request'
  | 'purchase-intent'
  | 'support-request'
  | 'general-discussion';

export type OpportunityStatus = 'new' | 'drafted' | 'approved' | 'published' | 'dismissed';

export interface RawOpportunityInput {
  platform: Platform;
  sourceUrl: string;
  /** Falls back to sourceUrl when a source can't supply a distinct
   * thread id -- see registry.ts's dedupe key. */
  threadId?: string;
  authorHandle: string;
  snippet: string;
}

export interface Opportunity {
  id: OpportunityId;
  platform: Platform;
  sourceUrl: string;
  threadId: string;
  authorHandle: string;
  snippet: string;
  keywords: string[];
  category: OpportunityCategory;
  /** 0-100, deterministic and explainable -- see
   * classification.ts:scoreOpportunityPriority. */
  priorityScore: number;
  status: OpportunityStatus;
  discoveredAt: string;
}

export type DraftStatus = 'pending' | 'approved' | 'rejected' | 'published';

export interface DuplicateWarning {
  type: 'thread-already-handled' | 'user-recently-engaged' | 'similar-reply-already-approved';
  detail: string;
}

export interface QualityScoreFactors {
  relevance: number;
  /** Lower is better; 0 = no detected risk. */
  spamRisk: number;
  /** Lower is better; 0 = no duplicate-prevention warnings raised. */
  duplicateRisk: number;
  linkAppropriateness: number;
  toneAndGrammar: number;
  brandConsistency: number;
}

export interface QualityScore {
  overall: number;
  factors: QualityScoreFactors;
}

export interface DraftReply {
  id: DraftReplyId;
  opportunityId: OpportunityId;
  body: string;
  includesLink: boolean;
  linkRationale?: string;
  suggestedDocs: string[];
  /** The ReplyAssistantProvider id that produced this draft -- see
   * replyAssistant.ts. */
  generatedBy: string;
  duplicateWarnings: DuplicateWarning[];
  quality: QualityScore;
  status: DraftStatus;
  createdAt: string;
  reviewedBy?: string;
  reviewedAt?: string;
  reviewNotes?: string;
}

export interface PublishedEngagement {
  id: PublishedEngagementId;
  opportunityId: OpportunityId;
  draftId: DraftReplyId;
  /** Where the human actually posted the reply -- supplied by that
   * human, never generated by this system. */
  publishedUrl: string;
  publishedBy: string;
  publishedAt: string;
  utmLink: string;
}

export type ConversionStage = 'website-visit' | 'signup' | 'trial' | 'paid-customer';

export interface ClickEvent {
  id: string;
  publishedEngagementId?: PublishedEngagementId;
  opportunityId?: OpportunityId;
  utmSource: string;
  utmMedium: string;
  utmCampaign: string;
  destinationUrl: string;
  clickedAt: string;
}

export interface ConversionEvent {
  id: string;
  stage: ConversionStage;
  opportunityId?: OpportunityId;
  occurredAt: string;
  metadata?: Record<string, unknown>;
}
