import { Metadata } from 'next';
import Link from 'next/link';
import { buildMetadata } from '../../../../lib/seo/metadata';

export const metadata: Metadata = buildMetadata({ path: '/legal/data-processing', title: 'Data Processing Policy | Oxiom', description: 'Oxiom data processing policy covering how invoice and financial data is processed, stored, and protected.' });

const sections = [
  ['Data Controller vs Processor', 'Customers generally act as the data controller for personal data and business records they submit to Oxiom Invoice Processing. Oxiom acts as a processor or service provider when handling that data on the customer’s behalf, except where Oxiom determines purposes and means independently for security, legal, or business administration needs.'],
  ['Processing Activities', 'Processing activities may include secure receipt, storage, extraction, validation, indexing, workflow routing, approval history capture, analytics, support diagnostics, and export of invoice-related records as required to operate the platform.'],
  ['Legal Basis', 'Where applicable, Oxiom relies on legal bases such as contract performance, legitimate interests, compliance with legal obligations, and customer instructions documented in applicable agreements or platform configurations.'],
  ['Retention', 'Data is retained according to customer instructions, contractual commitments, operational needs, audit requirements, and applicable law, including active storage, archive periods, and controlled deletion processes.'],
  ['Sub-processors', 'Oxiom may engage sub-processors for cloud hosting, observability, support tooling, and other operational services required to deliver the platform, subject to appropriate contractual and security obligations.'],
  ['Data Transfers', 'Where personal data is transferred across borders, Oxiom applies appropriate transfer safeguards such as contractual commitments, organizational controls, and technical protections.'],
  ['Security Measures', 'Oxiom maintains role-based access controls, encryption in transit and at rest, logging, monitoring, vulnerability management, and incident-response procedures designed to protect invoice and financial data.'],
];

export default function DataProcessingPolicyPage() {
  return <div className="min-h-screen bg-white"><div className="border-b border-slate-100 bg-slate-50 py-12 sm:py-16"><div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10"><h1 className="mb-4 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">Data Processing Policy</h1><p className="max-w-3xl text-lg text-slate-600">Review how Oxiom processes invoice, financial, and account data when delivering the Oxiom Invoice Processing platform to enterprise customers.</p></div></div><div className="mx-auto max-w-5xl px-6 py-16 sm:px-8 sm:py-20 lg:px-10"><div className="space-y-10">{sections.map(([title, body]) => (<section key={title}><h2 className="mb-4 text-2xl font-semibold text-slate-950">{title}</h2><p className="text-base leading-7 text-slate-600">{body}</p></section>))}</div></div><div className="border-t border-slate-100 bg-slate-50 py-16 sm:py-20"><div className="mx-auto max-w-5xl px-6 sm:px-8 lg:px-10"><div className="grid gap-6 md:grid-cols-3"><Link href="/legal/privacy" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Privacy Policy</h3></Link><Link href="/security" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Security overview</h3></Link><Link href="/contact" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Contact us</h3></Link></div></div></div></div>;
}
