import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Privacy Policy | Oxiom', description: 'Oxiom privacy policy covering data collection, processing, storage, and your rights under GDPR and CCPA.' };

const sections = [
  ['Data We Collect', 'Oxiom collects account information, contact details, authentication data, usage logs, support communications, and invoice-related business records that customers choose to upload or process through the platform. Depending on configuration, uploaded records may include vendor details, payment references, approver comments, and operational metadata needed to route, validate, store, and audit invoice workflows.'],
  ['How We Use Data', 'We use personal and business data to provide the service, secure customer accounts, operate workflows, deliver support, improve product performance, meet legal obligations, and communicate important service updates. Where permitted by law, limited account and usage information may also be used to analyze service adoption, prevent abuse, and develop new platform features.'],
  ['Data Sharing', 'Oxiom does not sell personal information. We may disclose data to trusted service providers, infrastructure partners, professional advisers, and public authorities when necessary to deliver the service, comply with legal obligations, or protect rights and safety.'],
  ['Data Retention', 'We retain account, operational, and invoice-related data for as long as needed to deliver the contracted service, maintain security records, satisfy audit needs, resolve disputes, and comply with applicable law. Customers can configure certain retention periods and deletion workflows subject to contractual and regulatory requirements.'],
  ['Your Rights Under GDPR and CCPA', 'Subject to applicable law, individuals may have rights to access, correct, delete, restrict, object to, or port personal data, as well as rights related to automated decision-making, non-discrimination, and authorized-agent requests. Requests can be submitted through our contact channels and may require identity or authority verification.'],
  ['Cookies', 'Oxiom uses essential cookies and similar technologies to maintain secure sessions, preserve preferences, support performance monitoring, and understand how the platform is used.'],
  ['Security', 'We maintain administrative, technical, and organizational safeguards designed to protect personal and business data against unauthorized access, loss, misuse, alteration, and disclosure, including encryption, access controls, logging, and incident-response practices.'],
  ['Contact', 'Questions about this Privacy Policy, your privacy rights, or Oxiom data practices may be directed to compliance@oxiom.ai or through the Oxiom contact page.'],
];

export default function PrivacyPolicyPage() {
  return <div className="min-h-screen bg-white"><div className="border-b border-slate-100 bg-slate-50 py-12 sm:py-16"><div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10"><h1 className="mb-4 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">Privacy Policy</h1><p className="max-w-3xl text-lg text-slate-600">This Privacy Policy explains how Oxiom collects, uses, protects, and manages personal and business data processed through Oxiom Invoice Processing.</p></div></div><div className="mx-auto max-w-5xl px-6 py-16 sm:px-8 sm:py-20 lg:px-10"><div className="space-y-10">{sections.map(([title, body]) => (<section key={title}><h2 className="mb-4 text-2xl font-semibold text-slate-950">{title}</h2><p className="text-base leading-7 text-slate-600">{body}</p></section>))}</div></div><div className="border-t border-slate-100 bg-slate-50 py-16 sm:py-20"><div className="mx-auto max-w-5xl px-6 sm:px-8 lg:px-10"><div className="grid gap-6 md:grid-cols-3"><Link href="/legal/cookies" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Cookie Policy</h3><p className="text-sm text-slate-600">Learn how Oxiom uses essential, functional, and analytics cookies.</p></Link><Link href="/legal/data-processing" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Data Processing Policy</h3><p className="text-sm text-slate-600">Review how invoice and financial data is processed, retained, and safeguarded.</p></Link><Link href="/contact" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Contact Oxiom</h3><p className="text-sm text-slate-600">Reach our support and compliance teams with privacy or contractual questions.</p></Link></div></div></div></div>;
}
