import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Cookie Policy | Oxiom', description: 'How Oxiom uses cookies and similar tracking technologies on our platform.' };

const types = [
  ['Essential', 'Necessary to authenticate users, maintain secure sessions, remember core settings, and support service reliability.'],
  ['Analytics', 'Help Oxiom understand usage patterns, identify performance issues, and improve product experience where legally permitted.'],
  ['Functional', 'Retain interface preferences, language selections, and workflow convenience settings for returning users.'],
];

export default function CookiePolicyPage() {
  return <div className="min-h-screen bg-white"><div className="border-b border-slate-100 bg-slate-50 py-12 sm:py-16"><div className="mx-auto max-w-7xl px-6 sm:px-8 lg:px-10"><h1 className="mb-4 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">Cookie Policy</h1><p className="max-w-3xl text-lg text-slate-600">This Cookie Policy explains how Oxiom uses cookies and similar technologies to operate, secure, and improve the Oxiom Invoice Processing platform.</p></div></div><div className="mx-auto max-w-5xl px-6 py-16 sm:px-8 sm:py-20 lg:px-10"><section className="mb-12"><h2 className="mb-4 text-2xl font-semibold text-slate-950">What Are Cookies</h2><p className="text-base leading-7 text-slate-600">Cookies are small text files or similar browser-based technologies that help websites and applications recognize a user or device, preserve preferences, support authentication, and improve service performance.</p></section><section className="mb-12"><h2 className="mb-6 text-2xl font-semibold text-slate-950">Types of Cookies</h2><div className="grid gap-6 md:grid-cols-3">{types.map(([title, description]) => (<div key={title} className="rounded-lg border border-slate-200 bg-white p-6"><h3 className="mb-3 text-xl font-semibold text-slate-950">{title}</h3><p className="text-sm leading-6 text-slate-600">{description}</p></div>))}</div></section><section className="mb-12"><h2 className="mb-4 text-2xl font-semibold text-slate-950">How to Control Cookies</h2><p className="text-base leading-7 text-slate-600">Users may manage certain cookie preferences through browser settings or consent mechanisms where required by law. Disabling essential cookies may affect sign-in, workflow continuity, and security-related features.</p></section><section><h2 className="mb-4 text-2xl font-semibold text-slate-950">Updates</h2><p className="text-base leading-7 text-slate-600">Oxiom may update this Cookie Policy to reflect changes in technology, legal obligations, or platform practices. Material updates will be published through the platform or other appropriate communication channels.</p></section></div><div className="border-t border-slate-100 bg-slate-50 py-16 sm:py-20"><div className="mx-auto max-w-5xl px-6 sm:px-8 lg:px-10"><div className="grid gap-6 md:grid-cols-3"><Link href="/legal/privacy" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Privacy Policy</h3></Link><Link href="/legal/data-processing" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Data Processing Policy</h3></Link><Link href="/support" className="rounded-lg border border-slate-200 bg-white p-6 hover:border-blue-300 hover:bg-blue-50"><h3 className="mb-2 text-lg font-semibold text-slate-950">Support hub</h3></Link></div></div></div></div>;
}
